package com.netposa.npconfig.datasource.model;

public class DeviceChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_channel.id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_channel.device_id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_channel.name
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_channel.chan_no
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    private String chanNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_channel.gb_id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    private String gbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device_channel.channel_type
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    private String channelType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_channel.id
     *
     * @return the value of dev_device_channel.id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_channel.id
     *
     * @param id the value for dev_device_channel.id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_channel.device_id
     *
     * @return the value of dev_device_channel.device_id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_channel.device_id
     *
     * @param deviceId the value for dev_device_channel.device_id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_channel.name
     *
     * @return the value of dev_device_channel.name
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_channel.name
     *
     * @param name the value for dev_device_channel.name
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_channel.chan_no
     *
     * @return the value of dev_device_channel.chan_no
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public String getChanNo() {
        return chanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_channel.chan_no
     *
     * @param chanNo the value for dev_device_channel.chan_no
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public void setChanNo(String chanNo) {
        this.chanNo = chanNo == null ? null : chanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_channel.gb_id
     *
     * @return the value of dev_device_channel.gb_id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public String getGbId() {
        return gbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_channel.gb_id
     *
     * @param gbId the value for dev_device_channel.gb_id
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public void setGbId(String gbId) {
        this.gbId = gbId == null ? null : gbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device_channel.channel_type
     *
     * @return the value of dev_device_channel.channel_type
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device_channel.channel_type
     *
     * @param channelType the value for dev_device_channel.channel_type
     *
     * @mbggenerated Mon Oct 29 18:28:19 CST 2018
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }
}