package com.royarn.mini.entity;


import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "dev_device")
public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.name
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.pin_yin
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String pinYin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.pin_yin_ad
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String pinYinAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.access
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String access;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.group_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.use_type
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String useType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.pau_service_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String pauServiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.service_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.device_type
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.channel_num
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer channelNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.status
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.sort
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.voice_talk
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer voiceTalk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.host
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.port
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.level
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.device_property
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private String deviceProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.synchro_clock
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer synchroClock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.heart_detection
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer heartDetection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.heart_timeout_times
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer heartTimeoutTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.heart_timeout_time
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer heartTimeoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.close_password_authentication
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer closePasswordAuthentication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.query_directory
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer queryDirectory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.subscribe_directory
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Integer subscribeDirectory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.expires
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Long expires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_device.forward_flag
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    private Boolean forwardFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.id
     *
     * @return the value of dev_device.id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.id
     *
     * @param id the value for dev_device.id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.name
     *
     * @return the value of dev_device.name
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.name
     *
     * @param name the value for dev_device.name
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.pin_yin
     *
     * @return the value of dev_device.pin_yin
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getPinYin() {
        return pinYin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.pin_yin
     *
     * @param pinYin the value for dev_device.pin_yin
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setPinYin(String pinYin) {
        this.pinYin = pinYin == null ? null : pinYin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.pin_yin_ad
     *
     * @return the value of dev_device.pin_yin_ad
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getPinYinAd() {
        return pinYinAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.pin_yin_ad
     *
     * @param pinYinAd the value for dev_device.pin_yin_ad
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setPinYinAd(String pinYinAd) {
        this.pinYinAd = pinYinAd == null ? null : pinYinAd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.access
     *
     * @return the value of dev_device.access
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getAccess() {
        return access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.access
     *
     * @param access the value for dev_device.access
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setAccess(String access) {
        this.access = access == null ? null : access.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.group_id
     *
     * @return the value of dev_device.group_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.group_id
     *
     * @param groupId the value for dev_device.group_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.use_type
     *
     * @return the value of dev_device.use_type
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.use_type
     *
     * @param useType the value for dev_device.use_type
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setUseType(String useType) {
        this.useType = useType == null ? null : useType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.pau_service_id
     *
     * @return the value of dev_device.pau_service_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getPauServiceId() {
        return pauServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.pau_service_id
     *
     * @param pauServiceId the value for dev_device.pau_service_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setPauServiceId(String pauServiceId) {
        this.pauServiceId = pauServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.service_id
     *
     * @return the value of dev_device.service_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.service_id
     *
     * @param serviceId the value for dev_device.service_id
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.device_type
     *
     * @return the value of dev_device.device_type
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.device_type
     *
     * @param deviceType the value for dev_device.device_type
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.channel_num
     *
     * @return the value of dev_device.channel_num
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getChannelNum() {
        return channelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.channel_num
     *
     * @param channelNum the value for dev_device.channel_num
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setChannelNum(Integer channelNum) {
        this.channelNum = channelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.status
     *
     * @return the value of dev_device.status
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.status
     *
     * @param status the value for dev_device.status
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.sort
     *
     * @return the value of dev_device.sort
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.sort
     *
     * @param sort the value for dev_device.sort
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.voice_talk
     *
     * @return the value of dev_device.voice_talk
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getVoiceTalk() {
        return voiceTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.voice_talk
     *
     * @param voiceTalk the value for dev_device.voice_talk
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setVoiceTalk(Integer voiceTalk) {
        this.voiceTalk = voiceTalk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.host
     *
     * @return the value of dev_device.host
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.host
     *
     * @param host the value for dev_device.host
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.port
     *
     * @return the value of dev_device.port
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.port
     *
     * @param port the value for dev_device.port
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.level
     *
     * @return the value of dev_device.level
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.level
     *
     * @param level the value for dev_device.level
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.device_property
     *
     * @return the value of dev_device.device_property
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public String getDeviceProperty() {
        return deviceProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.device_property
     *
     * @param deviceProperty the value for dev_device.device_property
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setDeviceProperty(String deviceProperty) {
        this.deviceProperty = deviceProperty == null ? null : deviceProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.synchro_clock
     *
     * @return the value of dev_device.synchro_clock
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getSynchroClock() {
        return synchroClock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.synchro_clock
     *
     * @param synchroClock the value for dev_device.synchro_clock
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setSynchroClock(Integer synchroClock) {
        this.synchroClock = synchroClock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.heart_detection
     *
     * @return the value of dev_device.heart_detection
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getHeartDetection() {
        return heartDetection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.heart_detection
     *
     * @param heartDetection the value for dev_device.heart_detection
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setHeartDetection(Integer heartDetection) {
        this.heartDetection = heartDetection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.heart_timeout_times
     *
     * @return the value of dev_device.heart_timeout_times
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getHeartTimeoutTimes() {
        return heartTimeoutTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.heart_timeout_times
     *
     * @param heartTimeoutTimes the value for dev_device.heart_timeout_times
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setHeartTimeoutTimes(Integer heartTimeoutTimes) {
        this.heartTimeoutTimes = heartTimeoutTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.heart_timeout_time
     *
     * @return the value of dev_device.heart_timeout_time
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getHeartTimeoutTime() {
        return heartTimeoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.heart_timeout_time
     *
     * @param heartTimeoutTime the value for dev_device.heart_timeout_time
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setHeartTimeoutTime(Integer heartTimeoutTime) {
        this.heartTimeoutTime = heartTimeoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.close_password_authentication
     *
     * @return the value of dev_device.close_password_authentication
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getClosePasswordAuthentication() {
        return closePasswordAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.close_password_authentication
     *
     * @param closePasswordAuthentication the value for dev_device.close_password_authentication
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setClosePasswordAuthentication(Integer closePasswordAuthentication) {
        this.closePasswordAuthentication = closePasswordAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.query_directory
     *
     * @return the value of dev_device.query_directory
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getQueryDirectory() {
        return queryDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.query_directory
     *
     * @param queryDirectory the value for dev_device.query_directory
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setQueryDirectory(Integer queryDirectory) {
        this.queryDirectory = queryDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.subscribe_directory
     *
     * @return the value of dev_device.subscribe_directory
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Integer getSubscribeDirectory() {
        return subscribeDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.subscribe_directory
     *
     * @param subscribeDirectory the value for dev_device.subscribe_directory
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setSubscribeDirectory(Integer subscribeDirectory) {
        this.subscribeDirectory = subscribeDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.expires
     *
     * @return the value of dev_device.expires
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Long getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.expires
     *
     * @param expires the value for dev_device.expires
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setExpires(Long expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_device.forward_flag
     *
     * @return the value of dev_device.forward_flag
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public Boolean getForwardFlag() {
        return forwardFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_device.forward_flag
     *
     * @param forwardFlag the value for dev_device.forward_flag
     *
     * @mbggenerated Mon Oct 29 11:53:16 CST 2018
     */
    public void setForwardFlag(Boolean forwardFlag) {
        this.forwardFlag = forwardFlag;
    }
}