package com.royarn.mini.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "dev_group")
public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.id
     *
     * @mbggenerated
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.mapping_code
     *
     * @mbggenerated
     */
    private String mappingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.relation_id
     *
     * @mbggenerated
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_groups.platform_id
     *
     * @mbggenerated
     */
    private String platformId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.id
     *
     * @return the value of other_groups.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.id
     *
     * @param id the value for other_groups.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.parent_id
     *
     * @return the value of other_groups.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.parent_id
     *
     * @param parentId the value for other_groups.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.name
     *
     * @return the value of other_groups.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.name
     *
     * @param name the value for other_groups.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.area_code
     *
     * @return the value of other_groups.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.area_code
     *
     * @param areaCode the value for other_groups.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.mapping_code
     *
     * @return the value of other_groups.mapping_code
     *
     * @mbggenerated
     */
    public String getMappingCode() {
        return mappingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.mapping_code
     *
     * @param mappingCode the value for other_groups.mapping_code
     *
     * @mbggenerated
     */
    public void setMappingCode(String mappingCode) {
        this.mappingCode = mappingCode == null ? null : mappingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.sort
     *
     * @return the value of other_groups.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.sort
     *
     * @param sort the value for other_groups.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.description
     *
     * @return the value of other_groups.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.description
     *
     * @param description the value for other_groups.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.code
     *
     * @return the value of other_groups.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.code
     *
     * @param code the value for other_groups.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.relation_id
     *
     * @return the value of other_groups.relation_id
     *
     * @mbggenerated
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.relation_id
     *
     * @param relationId the value for other_groups.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId == null ? null : relationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_groups.platform_id
     *
     * @return the value of other_groups.platform_id
     *
     * @mbggenerated
     */
    public String getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_groups.platform_id
     *
     * @param platformId the value for other_groups.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(String platformId) {
        this.platformId = platformId == null ? null : platformId.trim();
    }
}