package com.royarn.mini.entity;

public class LocalUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mail
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.img_head
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    private String imgHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.remark
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mail
     *
     * @return the value of t_user.mail
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mail
     *
     * @param mail the value for t_user.mail
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.img_head
     *
     * @return the value of t_user.img_head
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public String getImgHead() {
        return imgHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.img_head
     *
     * @param imgHead the value for t_user.img_head
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public void setImgHead(String imgHead) {
        this.imgHead = imgHead == null ? null : imgHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.remark
     *
     * @return the value of t_user.remark
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.remark
     *
     * @param remark the value for t_user.remark
     *
     * @mbggenerated Thu Oct 11 17:30:03 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}