package com.royarn.mini.entity;

public class MenuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.role_id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_role.menu_id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.id
     *
     * @return the value of t_menu_role.id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.id
     *
     * @param id the value for t_menu_role.id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.role_id
     *
     * @return the value of t_menu_role.role_id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.role_id
     *
     * @param roleId the value for t_menu_role.role_id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_role.menu_id
     *
     * @return the value of t_menu_role.menu_id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_role.menu_id
     *
     * @param menuId the value for t_menu_role.menu_id
     *
     * @mbggenerated Thu Oct 11 17:50:01 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }
}