package com.royarn.mini.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


@Document(collection = "dev_access_sdk")
public class SdkAccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_access_sdk.id
     *
     * @mbggenerated
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_access_sdk.protocol
     *
     * @mbggenerated
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_access_sdk.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_access_sdk.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_access_sdk.gb_id
     *
     * @mbggenerated
     */
    private String gbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_access_sdk.id
     *
     * @return the value of dev_access_sdk.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_access_sdk.id
     *
     * @param id the value for dev_access_sdk.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_access_sdk.protocol
     *
     * @return the value of dev_access_sdk.protocol
     *
     * @mbggenerated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_access_sdk.protocol
     *
     * @param protocol the value for dev_access_sdk.protocol
     *
     * @mbggenerated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_access_sdk.username
     *
     * @return the value of dev_access_sdk.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_access_sdk.username
     *
     * @param username the value for dev_access_sdk.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_access_sdk.password
     *
     * @return the value of dev_access_sdk.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_access_sdk.password
     *
     * @param password the value for dev_access_sdk.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_access_sdk.gb_id
     *
     * @return the value of dev_access_sdk.gb_id
     *
     * @mbggenerated
     */
    public String getGbId() {
        return gbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_access_sdk.gb_id
     *
     * @param gbId the value for dev_access_sdk.gb_id
     *
     * @mbggenerated
     */
    public void setGbId(String gbId) {
        this.gbId = gbId == null ? null : gbId.trim();
    }
}