package com.netposa.npconfig.datasource.model;

import java.util.UUID;

public class Server {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private UUID id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.type
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.status
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.gb_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer gbPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.gb_id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String gbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.node_code
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String nodeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.camera_max_digit
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer cameraMaxDigit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.group_id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.multicast
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer multicast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.service_version
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String serviceVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.db_host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String dbHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.kafka_host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String kafkaHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.kafka_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer kafkaPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.image_receiving_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer imageReceivingPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.name
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.cluster_ip
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String clusterIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.ptz_idle_time
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer ptzIdleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.is_cluster
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer isCluster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.monitor_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer monitorPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.monitor_username
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String monitorUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.monitor_password
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String monitorPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.database_address
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String databaseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.database_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private Integer databasePort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.memory_cycle
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String memoryCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.redundant_space
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String redundantSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.pau_component_list
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String pauComponentList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.keyboard_macro
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String keyboardMacro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.ext
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_server.loop_inspection
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    private String loopInspection;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.id
     *
     * @return the value of dev_server.id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.id
     *
     * @param id the value for dev_server.id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.type
     *
     * @return the value of dev_server.type
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.type
     *
     * @param type the value for dev_server.type
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.host
     *
     * @return the value of dev_server.host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.host
     *
     * @param host the value for dev_server.host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.port
     *
     * @return the value of dev_server.port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.port
     *
     * @param port the value for dev_server.port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.status
     *
     * @return the value of dev_server.status
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.status
     *
     * @param status the value for dev_server.status
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.gb_port
     *
     * @return the value of dev_server.gb_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getGbPort() {
        return gbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.gb_port
     *
     * @param gbPort the value for dev_server.gb_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setGbPort(Integer gbPort) {
        this.gbPort = gbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.gb_id
     *
     * @return the value of dev_server.gb_id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getGbId() {
        return gbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.gb_id
     *
     * @param gbId the value for dev_server.gb_id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setGbId(String gbId) {
        this.gbId = gbId == null ? null : gbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.node_code
     *
     * @return the value of dev_server.node_code
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getNodeCode() {
        return nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.node_code
     *
     * @param nodeCode the value for dev_server.node_code
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode == null ? null : nodeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.camera_max_digit
     *
     * @return the value of dev_server.camera_max_digit
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getCameraMaxDigit() {
        return cameraMaxDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.camera_max_digit
     *
     * @param cameraMaxDigit the value for dev_server.camera_max_digit
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setCameraMaxDigit(Integer cameraMaxDigit) {
        this.cameraMaxDigit = cameraMaxDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.group_id
     *
     * @return the value of dev_server.group_id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.group_id
     *
     * @param groupId the value for dev_server.group_id
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.multicast
     *
     * @return the value of dev_server.multicast
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getMulticast() {
        return multicast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.multicast
     *
     * @param multicast the value for dev_server.multicast
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setMulticast(Integer multicast) {
        this.multicast = multicast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.service_version
     *
     * @return the value of dev_server.service_version
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getServiceVersion() {
        return serviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.service_version
     *
     * @param serviceVersion the value for dev_server.service_version
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setServiceVersion(String serviceVersion) {
        this.serviceVersion = serviceVersion == null ? null : serviceVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.db_host
     *
     * @return the value of dev_server.db_host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getDbHost() {
        return dbHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.db_host
     *
     * @param dbHost the value for dev_server.db_host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setDbHost(String dbHost) {
        this.dbHost = dbHost == null ? null : dbHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.kafka_host
     *
     * @return the value of dev_server.kafka_host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getKafkaHost() {
        return kafkaHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.kafka_host
     *
     * @param kafkaHost the value for dev_server.kafka_host
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setKafkaHost(String kafkaHost) {
        this.kafkaHost = kafkaHost == null ? null : kafkaHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.kafka_port
     *
     * @return the value of dev_server.kafka_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getKafkaPort() {
        return kafkaPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.kafka_port
     *
     * @param kafkaPort the value for dev_server.kafka_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setKafkaPort(Integer kafkaPort) {
        this.kafkaPort = kafkaPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.image_receiving_port
     *
     * @return the value of dev_server.image_receiving_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getImageReceivingPort() {
        return imageReceivingPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.image_receiving_port
     *
     * @param imageReceivingPort the value for dev_server.image_receiving_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setImageReceivingPort(Integer imageReceivingPort) {
        this.imageReceivingPort = imageReceivingPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.name
     *
     * @return the value of dev_server.name
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.name
     *
     * @param name the value for dev_server.name
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.cluster_ip
     *
     * @return the value of dev_server.cluster_ip
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getClusterIp() {
        return clusterIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.cluster_ip
     *
     * @param clusterIp the value for dev_server.cluster_ip
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setClusterIp(String clusterIp) {
        this.clusterIp = clusterIp == null ? null : clusterIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.ptz_idle_time
     *
     * @return the value of dev_server.ptz_idle_time
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getPtzIdleTime() {
        return ptzIdleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.ptz_idle_time
     *
     * @param ptzIdleTime the value for dev_server.ptz_idle_time
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setPtzIdleTime(Integer ptzIdleTime) {
        this.ptzIdleTime = ptzIdleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.is_cluster
     *
     * @return the value of dev_server.is_cluster
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getIsCluster() {
        return isCluster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.is_cluster
     *
     * @param isCluster the value for dev_server.is_cluster
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setIsCluster(Integer isCluster) {
        this.isCluster = isCluster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.monitor_port
     *
     * @return the value of dev_server.monitor_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getMonitorPort() {
        return monitorPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.monitor_port
     *
     * @param monitorPort the value for dev_server.monitor_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setMonitorPort(Integer monitorPort) {
        this.monitorPort = monitorPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.monitor_username
     *
     * @return the value of dev_server.monitor_username
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getMonitorUsername() {
        return monitorUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.monitor_username
     *
     * @param monitorUsername the value for dev_server.monitor_username
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setMonitorUsername(String monitorUsername) {
        this.monitorUsername = monitorUsername == null ? null : monitorUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.monitor_password
     *
     * @return the value of dev_server.monitor_password
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getMonitorPassword() {
        return monitorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.monitor_password
     *
     * @param monitorPassword the value for dev_server.monitor_password
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setMonitorPassword(String monitorPassword) {
        this.monitorPassword = monitorPassword == null ? null : monitorPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.database_address
     *
     * @return the value of dev_server.database_address
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getDatabaseAddress() {
        return databaseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.database_address
     *
     * @param databaseAddress the value for dev_server.database_address
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setDatabaseAddress(String databaseAddress) {
        this.databaseAddress = databaseAddress == null ? null : databaseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.database_port
     *
     * @return the value of dev_server.database_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public Integer getDatabasePort() {
        return databasePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.database_port
     *
     * @param databasePort the value for dev_server.database_port
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setDatabasePort(Integer databasePort) {
        this.databasePort = databasePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.memory_cycle
     *
     * @return the value of dev_server.memory_cycle
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getMemoryCycle() {
        return memoryCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.memory_cycle
     *
     * @param memoryCycle the value for dev_server.memory_cycle
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setMemoryCycle(String memoryCycle) {
        this.memoryCycle = memoryCycle == null ? null : memoryCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.redundant_space
     *
     * @return the value of dev_server.redundant_space
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getRedundantSpace() {
        return redundantSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.redundant_space
     *
     * @param redundantSpace the value for dev_server.redundant_space
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setRedundantSpace(String redundantSpace) {
        this.redundantSpace = redundantSpace == null ? null : redundantSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.pau_component_list
     *
     * @return the value of dev_server.pau_component_list
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getPauComponentList() {
        return pauComponentList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.pau_component_list
     *
     * @param pauComponentList the value for dev_server.pau_component_list
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setPauComponentList(String pauComponentList) {
        this.pauComponentList = pauComponentList == null ? null : pauComponentList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.keyboard_macro
     *
     * @return the value of dev_server.keyboard_macro
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getKeyboardMacro() {
        return keyboardMacro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.keyboard_macro
     *
     * @param keyboardMacro the value for dev_server.keyboard_macro
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setKeyboardMacro(String keyboardMacro) {
        this.keyboardMacro = keyboardMacro == null ? null : keyboardMacro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.ext
     *
     * @return the value of dev_server.ext
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.ext
     *
     * @param ext the value for dev_server.ext
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_server.loop_inspection
     *
     * @return the value of dev_server.loop_inspection
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public String getLoopInspection() {
        return loopInspection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_server.loop_inspection
     *
     * @param loopInspection the value for dev_server.loop_inspection
     *
     * @mbggenerated Tue Dec 04 13:44:02 CST 2018
     */
    public void setLoopInspection(String loopInspection) {
        this.loopInspection = loopInspection == null ? null : loopInspection.trim();
    }
}