package com.royarn.mini.entity;

import java.util.ArrayList;
import java.util.List;

public class TDeviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public TDeviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPinYinIsNull() {
            addCriterion("pin_yin is null");
            return (Criteria) this;
        }

        public Criteria andPinYinIsNotNull() {
            addCriterion("pin_yin is not null");
            return (Criteria) this;
        }

        public Criteria andPinYinEqualTo(String value) {
            addCriterion("pin_yin =", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotEqualTo(String value) {
            addCriterion("pin_yin <>", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinGreaterThan(String value) {
            addCriterion("pin_yin >", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinGreaterThanOrEqualTo(String value) {
            addCriterion("pin_yin >=", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinLessThan(String value) {
            addCriterion("pin_yin <", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinLessThanOrEqualTo(String value) {
            addCriterion("pin_yin <=", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinLike(String value) {
            addCriterion("pin_yin like", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotLike(String value) {
            addCriterion("pin_yin not like", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinIn(List<String> values) {
            addCriterion("pin_yin in", values, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotIn(List<String> values) {
            addCriterion("pin_yin not in", values, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinBetween(String value1, String value2) {
            addCriterion("pin_yin between", value1, value2, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotBetween(String value1, String value2) {
            addCriterion("pin_yin not between", value1, value2, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinAdIsNull() {
            addCriterion("pin_yin_ad is null");
            return (Criteria) this;
        }

        public Criteria andPinYinAdIsNotNull() {
            addCriterion("pin_yin_ad is not null");
            return (Criteria) this;
        }

        public Criteria andPinYinAdEqualTo(String value) {
            addCriterion("pin_yin_ad =", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdNotEqualTo(String value) {
            addCriterion("pin_yin_ad <>", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdGreaterThan(String value) {
            addCriterion("pin_yin_ad >", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdGreaterThanOrEqualTo(String value) {
            addCriterion("pin_yin_ad >=", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdLessThan(String value) {
            addCriterion("pin_yin_ad <", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdLessThanOrEqualTo(String value) {
            addCriterion("pin_yin_ad <=", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdLike(String value) {
            addCriterion("pin_yin_ad like", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdNotLike(String value) {
            addCriterion("pin_yin_ad not like", value, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdIn(List<String> values) {
            addCriterion("pin_yin_ad in", values, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdNotIn(List<String> values) {
            addCriterion("pin_yin_ad not in", values, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdBetween(String value1, String value2) {
            addCriterion("pin_yin_ad between", value1, value2, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andPinYinAdNotBetween(String value1, String value2) {
            addCriterion("pin_yin_ad not between", value1, value2, "pinYinAd");
            return (Criteria) this;
        }

        public Criteria andAccessIsNull() {
            addCriterion("`access` is null");
            return (Criteria) this;
        }

        public Criteria andAccessIsNotNull() {
            addCriterion("`access` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessEqualTo(String value) {
            addCriterion("`access` =", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotEqualTo(String value) {
            addCriterion("`access` <>", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessGreaterThan(String value) {
            addCriterion("`access` >", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessGreaterThanOrEqualTo(String value) {
            addCriterion("`access` >=", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessLessThan(String value) {
            addCriterion("`access` <", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessLessThanOrEqualTo(String value) {
            addCriterion("`access` <=", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessLike(String value) {
            addCriterion("`access` like", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotLike(String value) {
            addCriterion("`access` not like", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessIn(List<String> values) {
            addCriterion("`access` in", values, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotIn(List<String> values) {
            addCriterion("`access` not in", values, "access");
            return (Criteria) this;
        }

        public Criteria andAccessBetween(String value1, String value2) {
            addCriterion("`access` between", value1, value2, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotBetween(String value1, String value2) {
            addCriterion("`access` not between", value1, value2, "access");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNull() {
            addCriterion("use_type is null");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNotNull() {
            addCriterion("use_type is not null");
            return (Criteria) this;
        }

        public Criteria andUseTypeEqualTo(String value) {
            addCriterion("use_type =", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotEqualTo(String value) {
            addCriterion("use_type <>", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThan(String value) {
            addCriterion("use_type >", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("use_type >=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThan(String value) {
            addCriterion("use_type <", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThanOrEqualTo(String value) {
            addCriterion("use_type <=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLike(String value) {
            addCriterion("use_type like", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotLike(String value) {
            addCriterion("use_type not like", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeIn(List<String> values) {
            addCriterion("use_type in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotIn(List<String> values) {
            addCriterion("use_type not in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeBetween(String value1, String value2) {
            addCriterion("use_type between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotBetween(String value1, String value2) {
            addCriterion("use_type not between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdIsNull() {
            addCriterion("pau_service_id is null");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdIsNotNull() {
            addCriterion("pau_service_id is not null");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdEqualTo(String value) {
            addCriterion("pau_service_id =", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdNotEqualTo(String value) {
            addCriterion("pau_service_id <>", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdGreaterThan(String value) {
            addCriterion("pau_service_id >", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("pau_service_id >=", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdLessThan(String value) {
            addCriterion("pau_service_id <", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdLessThanOrEqualTo(String value) {
            addCriterion("pau_service_id <=", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdLike(String value) {
            addCriterion("pau_service_id like", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdNotLike(String value) {
            addCriterion("pau_service_id not like", value, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdIn(List<String> values) {
            addCriterion("pau_service_id in", values, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdNotIn(List<String> values) {
            addCriterion("pau_service_id not in", values, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdBetween(String value1, String value2) {
            addCriterion("pau_service_id between", value1, value2, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andPauServiceIdNotBetween(String value1, String value2) {
            addCriterion("pau_service_id not between", value1, value2, "pauServiceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNull() {
            addCriterion("service_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {
            addCriterion("service_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(String value) {
            addCriterion("service_id =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(String value) {
            addCriterion("service_id <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(String value) {
            addCriterion("service_id >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("service_id >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(String value) {
            addCriterion("service_id <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(String value) {
            addCriterion("service_id <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLike(String value) {
            addCriterion("service_id like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotLike(String value) {
            addCriterion("service_id not like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<String> values) {
            addCriterion("service_id in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<String> values) {
            addCriterion("service_id not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(String value1, String value2) {
            addCriterion("service_id between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(String value1, String value2) {
            addCriterion("service_id not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("device_type is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("device_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("device_type =", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("device_type <>", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("device_type >", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("device_type >=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("device_type <", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("device_type <=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("device_type like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("device_type not like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIn(List<String> values) {
            addCriterion("device_type in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotIn(List<String> values) {
            addCriterion("device_type not in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("device_type between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("device_type not between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andChannelNumIsNull() {
            addCriterion("channel_num is null");
            return (Criteria) this;
        }

        public Criteria andChannelNumIsNotNull() {
            addCriterion("channel_num is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNumEqualTo(Integer value) {
            addCriterion("channel_num =", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotEqualTo(Integer value) {
            addCriterion("channel_num <>", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumGreaterThan(Integer value) {
            addCriterion("channel_num >", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_num >=", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumLessThan(Integer value) {
            addCriterion("channel_num <", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumLessThanOrEqualTo(Integer value) {
            addCriterion("channel_num <=", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumIn(List<Integer> values) {
            addCriterion("channel_num in", values, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotIn(List<Integer> values) {
            addCriterion("channel_num not in", values, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumBetween(Integer value1, Integer value2) {
            addCriterion("channel_num between", value1, value2, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_num not between", value1, value2, "channelNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Long value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Long value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Long value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Long value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Long value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Long value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Long> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Long> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Long value1, Long value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Long value1, Long value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkIsNull() {
            addCriterion("voice_talk is null");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkIsNotNull() {
            addCriterion("voice_talk is not null");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkEqualTo(Integer value) {
            addCriterion("voice_talk =", value, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkNotEqualTo(Integer value) {
            addCriterion("voice_talk <>", value, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkGreaterThan(Integer value) {
            addCriterion("voice_talk >", value, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkGreaterThanOrEqualTo(Integer value) {
            addCriterion("voice_talk >=", value, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkLessThan(Integer value) {
            addCriterion("voice_talk <", value, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkLessThanOrEqualTo(Integer value) {
            addCriterion("voice_talk <=", value, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkIn(List<Integer> values) {
            addCriterion("voice_talk in", values, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkNotIn(List<Integer> values) {
            addCriterion("voice_talk not in", values, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkBetween(Integer value1, Integer value2) {
            addCriterion("voice_talk between", value1, value2, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andVoiceTalkNotBetween(Integer value1, Integer value2) {
            addCriterion("voice_talk not between", value1, value2, "voiceTalk");
            return (Criteria) this;
        }

        public Criteria andHostIsNull() {
            addCriterion("`host` is null");
            return (Criteria) this;
        }

        public Criteria andHostIsNotNull() {
            addCriterion("`host` is not null");
            return (Criteria) this;
        }

        public Criteria andHostEqualTo(String value) {
            addCriterion("`host` =", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostNotEqualTo(String value) {
            addCriterion("`host` <>", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostGreaterThan(String value) {
            addCriterion("`host` >", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostGreaterThanOrEqualTo(String value) {
            addCriterion("`host` >=", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostLessThan(String value) {
            addCriterion("`host` <", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostLessThanOrEqualTo(String value) {
            addCriterion("`host` <=", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostLike(String value) {
            addCriterion("`host` like", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostNotLike(String value) {
            addCriterion("`host` not like", value, "host");
            return (Criteria) this;
        }

        public Criteria andHostIn(List<String> values) {
            addCriterion("`host` in", values, "host");
            return (Criteria) this;
        }

        public Criteria andHostNotIn(List<String> values) {
            addCriterion("`host` not in", values, "host");
            return (Criteria) this;
        }

        public Criteria andHostBetween(String value1, String value2) {
            addCriterion("`host` between", value1, value2, "host");
            return (Criteria) this;
        }

        public Criteria andHostNotBetween(String value1, String value2) {
            addCriterion("`host` not between", value1, value2, "host");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(Integer value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(Integer value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(Integer value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(Integer value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(Integer value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<Integer> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<Integer> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(Integer value1, Integer value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(Integer value1, Integer value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("`level` is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("`level` is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("`level` =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("`level` <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("`level` >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`level` >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("`level` <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("`level` <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("`level` like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("`level` not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("`level` in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("`level` not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("`level` between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("`level` not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyIsNull() {
            addCriterion("device_property is null");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyIsNotNull() {
            addCriterion("device_property is not null");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyEqualTo(String value) {
            addCriterion("device_property =", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyNotEqualTo(String value) {
            addCriterion("device_property <>", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyGreaterThan(String value) {
            addCriterion("device_property >", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyGreaterThanOrEqualTo(String value) {
            addCriterion("device_property >=", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyLessThan(String value) {
            addCriterion("device_property <", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyLessThanOrEqualTo(String value) {
            addCriterion("device_property <=", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyLike(String value) {
            addCriterion("device_property like", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyNotLike(String value) {
            addCriterion("device_property not like", value, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyIn(List<String> values) {
            addCriterion("device_property in", values, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyNotIn(List<String> values) {
            addCriterion("device_property not in", values, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyBetween(String value1, String value2) {
            addCriterion("device_property between", value1, value2, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andDevicePropertyNotBetween(String value1, String value2) {
            addCriterion("device_property not between", value1, value2, "deviceProperty");
            return (Criteria) this;
        }

        public Criteria andSynchroClockIsNull() {
            addCriterion("synchro_clock is null");
            return (Criteria) this;
        }

        public Criteria andSynchroClockIsNotNull() {
            addCriterion("synchro_clock is not null");
            return (Criteria) this;
        }

        public Criteria andSynchroClockEqualTo(Integer value) {
            addCriterion("synchro_clock =", value, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockNotEqualTo(Integer value) {
            addCriterion("synchro_clock <>", value, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockGreaterThan(Integer value) {
            addCriterion("synchro_clock >", value, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockGreaterThanOrEqualTo(Integer value) {
            addCriterion("synchro_clock >=", value, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockLessThan(Integer value) {
            addCriterion("synchro_clock <", value, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockLessThanOrEqualTo(Integer value) {
            addCriterion("synchro_clock <=", value, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockIn(List<Integer> values) {
            addCriterion("synchro_clock in", values, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockNotIn(List<Integer> values) {
            addCriterion("synchro_clock not in", values, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockBetween(Integer value1, Integer value2) {
            addCriterion("synchro_clock between", value1, value2, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andSynchroClockNotBetween(Integer value1, Integer value2) {
            addCriterion("synchro_clock not between", value1, value2, "synchroClock");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionIsNull() {
            addCriterion("heart_detection is null");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionIsNotNull() {
            addCriterion("heart_detection is not null");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionEqualTo(Integer value) {
            addCriterion("heart_detection =", value, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionNotEqualTo(Integer value) {
            addCriterion("heart_detection <>", value, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionGreaterThan(Integer value) {
            addCriterion("heart_detection >", value, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("heart_detection >=", value, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionLessThan(Integer value) {
            addCriterion("heart_detection <", value, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionLessThanOrEqualTo(Integer value) {
            addCriterion("heart_detection <=", value, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionIn(List<Integer> values) {
            addCriterion("heart_detection in", values, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionNotIn(List<Integer> values) {
            addCriterion("heart_detection not in", values, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionBetween(Integer value1, Integer value2) {
            addCriterion("heart_detection between", value1, value2, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartDetectionNotBetween(Integer value1, Integer value2) {
            addCriterion("heart_detection not between", value1, value2, "heartDetection");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesIsNull() {
            addCriterion("heart_timeout_times is null");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesIsNotNull() {
            addCriterion("heart_timeout_times is not null");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesEqualTo(Integer value) {
            addCriterion("heart_timeout_times =", value, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesNotEqualTo(Integer value) {
            addCriterion("heart_timeout_times <>", value, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesGreaterThan(Integer value) {
            addCriterion("heart_timeout_times >", value, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("heart_timeout_times >=", value, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesLessThan(Integer value) {
            addCriterion("heart_timeout_times <", value, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesLessThanOrEqualTo(Integer value) {
            addCriterion("heart_timeout_times <=", value, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesIn(List<Integer> values) {
            addCriterion("heart_timeout_times in", values, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesNotIn(List<Integer> values) {
            addCriterion("heart_timeout_times not in", values, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesBetween(Integer value1, Integer value2) {
            addCriterion("heart_timeout_times between", value1, value2, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("heart_timeout_times not between", value1, value2, "heartTimeoutTimes");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeIsNull() {
            addCriterion("heart_timeout_time is null");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeIsNotNull() {
            addCriterion("heart_timeout_time is not null");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeEqualTo(Integer value) {
            addCriterion("heart_timeout_time =", value, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeNotEqualTo(Integer value) {
            addCriterion("heart_timeout_time <>", value, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeGreaterThan(Integer value) {
            addCriterion("heart_timeout_time >", value, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("heart_timeout_time >=", value, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeLessThan(Integer value) {
            addCriterion("heart_timeout_time <", value, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeLessThanOrEqualTo(Integer value) {
            addCriterion("heart_timeout_time <=", value, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeIn(List<Integer> values) {
            addCriterion("heart_timeout_time in", values, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeNotIn(List<Integer> values) {
            addCriterion("heart_timeout_time not in", values, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeBetween(Integer value1, Integer value2) {
            addCriterion("heart_timeout_time between", value1, value2, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andHeartTimeoutTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("heart_timeout_time not between", value1, value2, "heartTimeoutTime");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationIsNull() {
            addCriterion("close_password_authentication is null");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationIsNotNull() {
            addCriterion("close_password_authentication is not null");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationEqualTo(Integer value) {
            addCriterion("close_password_authentication =", value, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationNotEqualTo(Integer value) {
            addCriterion("close_password_authentication <>", value, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationGreaterThan(Integer value) {
            addCriterion("close_password_authentication >", value, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationGreaterThanOrEqualTo(Integer value) {
            addCriterion("close_password_authentication >=", value, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationLessThan(Integer value) {
            addCriterion("close_password_authentication <", value, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationLessThanOrEqualTo(Integer value) {
            addCriterion("close_password_authentication <=", value, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationIn(List<Integer> values) {
            addCriterion("close_password_authentication in", values, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationNotIn(List<Integer> values) {
            addCriterion("close_password_authentication not in", values, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationBetween(Integer value1, Integer value2) {
            addCriterion("close_password_authentication between", value1, value2, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andClosePasswordAuthenticationNotBetween(Integer value1, Integer value2) {
            addCriterion("close_password_authentication not between", value1, value2, "closePasswordAuthentication");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryIsNull() {
            addCriterion("query_directory is null");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryIsNotNull() {
            addCriterion("query_directory is not null");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryEqualTo(Integer value) {
            addCriterion("query_directory =", value, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryNotEqualTo(Integer value) {
            addCriterion("query_directory <>", value, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryGreaterThan(Integer value) {
            addCriterion("query_directory >", value, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("query_directory >=", value, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryLessThan(Integer value) {
            addCriterion("query_directory <", value, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryLessThanOrEqualTo(Integer value) {
            addCriterion("query_directory <=", value, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryIn(List<Integer> values) {
            addCriterion("query_directory in", values, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryNotIn(List<Integer> values) {
            addCriterion("query_directory not in", values, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryBetween(Integer value1, Integer value2) {
            addCriterion("query_directory between", value1, value2, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andQueryDirectoryNotBetween(Integer value1, Integer value2) {
            addCriterion("query_directory not between", value1, value2, "queryDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryIsNull() {
            addCriterion("subscribe_directory is null");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryIsNotNull() {
            addCriterion("subscribe_directory is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryEqualTo(Integer value) {
            addCriterion("subscribe_directory =", value, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryNotEqualTo(Integer value) {
            addCriterion("subscribe_directory <>", value, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryGreaterThan(Integer value) {
            addCriterion("subscribe_directory >", value, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("subscribe_directory >=", value, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryLessThan(Integer value) {
            addCriterion("subscribe_directory <", value, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryLessThanOrEqualTo(Integer value) {
            addCriterion("subscribe_directory <=", value, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryIn(List<Integer> values) {
            addCriterion("subscribe_directory in", values, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryNotIn(List<Integer> values) {
            addCriterion("subscribe_directory not in", values, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryBetween(Integer value1, Integer value2) {
            addCriterion("subscribe_directory between", value1, value2, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andSubscribeDirectoryNotBetween(Integer value1, Integer value2) {
            addCriterion("subscribe_directory not between", value1, value2, "subscribeDirectory");
            return (Criteria) this;
        }

        public Criteria andExpiresIsNull() {
            addCriterion("expires is null");
            return (Criteria) this;
        }

        public Criteria andExpiresIsNotNull() {
            addCriterion("expires is not null");
            return (Criteria) this;
        }

        public Criteria andExpiresEqualTo(Long value) {
            addCriterion("expires =", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresNotEqualTo(Long value) {
            addCriterion("expires <>", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresGreaterThan(Long value) {
            addCriterion("expires >", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresGreaterThanOrEqualTo(Long value) {
            addCriterion("expires >=", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresLessThan(Long value) {
            addCriterion("expires <", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresLessThanOrEqualTo(Long value) {
            addCriterion("expires <=", value, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresIn(List<Long> values) {
            addCriterion("expires in", values, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresNotIn(List<Long> values) {
            addCriterion("expires not in", values, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresBetween(Long value1, Long value2) {
            addCriterion("expires between", value1, value2, "expires");
            return (Criteria) this;
        }

        public Criteria andExpiresNotBetween(Long value1, Long value2) {
            addCriterion("expires not between", value1, value2, "expires");
            return (Criteria) this;
        }

        public Criteria andForwardFlagIsNull() {
            addCriterion("forward_flag is null");
            return (Criteria) this;
        }

        public Criteria andForwardFlagIsNotNull() {
            addCriterion("forward_flag is not null");
            return (Criteria) this;
        }

        public Criteria andForwardFlagEqualTo(Boolean value) {
            addCriterion("forward_flag =", value, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagNotEqualTo(Boolean value) {
            addCriterion("forward_flag <>", value, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagGreaterThan(Boolean value) {
            addCriterion("forward_flag >", value, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("forward_flag >=", value, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagLessThan(Boolean value) {
            addCriterion("forward_flag <", value, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("forward_flag <=", value, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagIn(List<Boolean> values) {
            addCriterion("forward_flag in", values, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagNotIn(List<Boolean> values) {
            addCriterion("forward_flag not in", values, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("forward_flag between", value1, value2, "forwardFlag");
            return (Criteria) this;
        }

        public Criteria andForwardFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("forward_flag not between", value1, value2, "forwardFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dev_device
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 28 16:41:25 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}