package com.royarn.mini.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

@Document(collection = "t_user")
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.pin_yin
     *
     * @mbggenerated
     */
    private String pinYin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.pin_yin_ad
     *
     * @mbggenerated
     */
    private String pinYinAd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.raw_password
     *
     * @mbggenerated
     */
    private String rawPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ex_user_id
     *
     * @mbggenerated
     */
    private String exUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.org_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.finger_status
     *
     * @mbggenerated
     */
    private Integer fingerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id_card_no
     *
     * @mbggenerated
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone_no
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.max_way
     *
     * @mbggenerated
     */
    private Integer maxWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gb_id
     *
     * @mbggenerated
     */
    private String gbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_code
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.video_limit
     *
     * @mbggenerated
     */
    private String videoLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.yearly_check
     *
     * @mbggenerated
     */
    private Integer yearlyCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.yearly_status
     *
     * @mbggenerated
     */
    private String yearlyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.node_id
     *
     * @mbggenerated
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.permit_repeat_login
     *
     * @mbggenerated
     */
    private Integer permitRepeatLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.finger_vein
     *
     * @mbggenerated
     */
    private String fingerVein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.safe_mac
     *
     * @mbggenerated
     */
    private String safeMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.safe_ip
     *
     * @mbggenerated
     */
    private String safeIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reserved
     *
     * @mbggenerated
     */
    private String reserved;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pin_yin
     *
     * @return the value of users.pin_yin
     *
     * @mbggenerated
     */
    public String getPinYin() {
        return pinYin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pin_yin
     *
     * @param pinYin the value for users.pin_yin
     *
     * @mbggenerated
     */
    public void setPinYin(String pinYin) {
        this.pinYin = pinYin == null ? null : pinYin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pin_yin_ad
     *
     * @return the value of users.pin_yin_ad
     *
     * @mbggenerated
     */
    public String getPinYinAd() {
        return pinYinAd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pin_yin_ad
     *
     * @param pinYinAd the value for users.pin_yin_ad
     *
     * @mbggenerated
     */
    public void setPinYinAd(String pinYinAd) {
        this.pinYinAd = pinYinAd == null ? null : pinYinAd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_name
     *
     * @return the value of users.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_name
     *
     * @param loginName the value for users.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.raw_password
     *
     * @return the value of users.raw_password
     *
     * @mbggenerated
     */
    public String getRawPassword() {
        return rawPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.raw_password
     *
     * @param rawPassword the value for users.raw_password
     *
     * @mbggenerated
     */
    public void setRawPassword(String rawPassword) {
        this.rawPassword = rawPassword == null ? null : rawPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ex_user_id
     *
     * @return the value of users.ex_user_id
     *
     * @mbggenerated
     */
    public String getExUserId() {
        return exUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ex_user_id
     *
     * @param exUserId the value for users.ex_user_id
     *
     * @mbggenerated
     */
    public void setExUserId(String exUserId) {
        this.exUserId = exUserId == null ? null : exUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.tel
     *
     * @return the value of users.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.tel
     *
     * @param tel the value for users.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.org_id
     *
     * @return the value of users.org_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.org_id
     *
     * @param orgId the value for users.org_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {this.groupId = groupId; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.modify_time
     *
     * @return the value of users.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.modify_time
     *
     * @param modifyTime the value for users.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.finger_status
     *
     * @return the value of users.finger_status
     *
     * @mbggenerated
     */
    public Integer getFingerStatus() {
        return fingerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.finger_status
     *
     * @param fingerStatus the value for users.finger_status
     *
     * @mbggenerated
     */
    public void setFingerStatus(Integer fingerStatus) {
        this.fingerStatus = fingerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.level
     *
     * @return the value of users.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.level
     *
     * @param level the value for users.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id_card_no
     *
     * @return the value of users.id_card_no
     *
     * @mbggenerated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id_card_no
     *
     * @param idCardNo the value for users.id_card_no
     *
     * @mbggenerated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone_no
     *
     * @return the value of users.phone_no
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone_no
     *
     * @param phoneNo the value for users.phone_no
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.start_time
     *
     * @return the value of users.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.start_time
     *
     * @param startTime the value for users.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.end_time
     *
     * @return the value of users.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.end_time
     *
     * @param endTime the value for users.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.max_way
     *
     * @return the value of users.max_way
     *
     * @mbggenerated
     */
    public Integer getMaxWay() {
        return maxWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.max_way
     *
     * @param maxWay the value for users.max_way
     *
     * @mbggenerated
     */
    public void setMaxWay(Integer maxWay) {
        this.maxWay = maxWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gb_id
     *
     * @return the value of users.gb_id
     *
     * @mbggenerated
     */
    public String getGbId() {
        return gbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gb_id
     *
     * @param gbId the value for users.gb_id
     *
     * @mbggenerated
     */
    public void setGbId(String gbId) {
        this.gbId = gbId == null ? null : gbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_code
     *
     * @return the value of users.user_code
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_code
     *
     * @param userCode the value for users.user_code
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.video_limit
     *
     * @return the value of users.video_limit
     *
     * @mbggenerated
     */
    public String getVideoLimit() {
        return videoLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.video_limit
     *
     * @param videoLimit the value for users.video_limit
     *
     * @mbggenerated
     */
    public void setVideoLimit(String videoLimit) {
        this.videoLimit = videoLimit == null ? null : videoLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.yearly_check
     *
     * @return the value of users.yearly_check
     *
     * @mbggenerated
     */
    public Integer getYearlyCheck() {
        return yearlyCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.yearly_check
     *
     * @param yearlyCheck the value for users.yearly_check
     *
     * @mbggenerated
     */
    public void setYearlyCheck(Integer yearlyCheck) {
        this.yearlyCheck = yearlyCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.yearly_status
     *
     * @return the value of users.yearly_status
     *
     * @mbggenerated
     */
    public String getYearlyStatus() {
        return yearlyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.yearly_status
     *
     * @param yearlyStatus the value for users.yearly_status
     *
     * @mbggenerated
     */
    public void setYearlyStatus(String yearlyStatus) {
        this.yearlyStatus = yearlyStatus == null ? null : yearlyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_time
     *
     * @return the value of users.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_time
     *
     * @param loginTime the value for users.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.node_id
     *
     * @return the value of users.node_id
     *
     * @mbggenerated
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.node_id
     *
     * @param nodeId the value for users.node_id
     *
     * @mbggenerated
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.permit_repeat_login
     *
     * @return the value of users.permit_repeat_login
     *
     * @mbggenerated
     */
    public Integer getPermitRepeatLogin() {
        return permitRepeatLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.permit_repeat_login
     *
     * @param permitRepeatLogin the value for users.permit_repeat_login
     *
     * @mbggenerated
     */
    public void setPermitRepeatLogin(Integer permitRepeatLogin) {
        this.permitRepeatLogin = permitRepeatLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.finger_vein
     *
     * @return the value of users.finger_vein
     *
     * @mbggenerated
     */
    public String getFingerVein() {
        return fingerVein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.finger_vein
     *
     * @param fingerVein the value for users.finger_vein
     *
     * @mbggenerated
     */
    public void setFingerVein(String fingerVein) {
        this.fingerVein = fingerVein == null ? null : fingerVein.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.safe_mac
     *
     * @return the value of users.safe_mac
     *
     * @mbggenerated
     */
    public String getSafeMac() {
        return safeMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.safe_mac
     *
     * @param safeMac the value for users.safe_mac
     *
     * @mbggenerated
     */
    public void setSafeMac(String safeMac) {
        this.safeMac = safeMac == null ? null : safeMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.safe_ip
     *
     * @return the value of users.safe_ip
     *
     * @mbggenerated
     */
    public String getSafeIp() {
        return safeIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.safe_ip
     *
     * @param safeIp the value for users.safe_ip
     *
     * @mbggenerated
     */
    public void setSafeIp(String safeIp) {
        this.safeIp = safeIp == null ? null : safeIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.comment
     *
     * @return the value of users.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.comment
     *
     * @param comment the value for users.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reserved
     *
     * @return the value of users.reserved
     *
     * @mbggenerated
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reserved
     *
     * @param reserved the value for users.reserved
     *
     * @mbggenerated
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }
}