package com.royarn.mini.dao;

import com.royarn.mini.entity.DevCamera;
import com.royarn.mini.entity.DevCameraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevCameraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int countByExample(DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int deleteByExample(DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int insert(DevCamera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int insertSelective(DevCamera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    List<DevCamera> selectByExampleWithBLOBs(DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    List<DevCamera> selectByExample(DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    DevCamera selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") DevCamera record, @Param("example") DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DevCamera record, @Param("example") DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExample(@Param("record") DevCamera record, @Param("example") DevCameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKeySelective(DevCamera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DevCamera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device_camera
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKey(DevCamera record);

    void batchInsert(@Param("cameras") List<DevCamera> cameras);
}