package com.royarn.mini.dao;

import com.royarn.mini.entity.DevDevice;
import com.royarn.mini.entity.DevDeviceExample;
import java.util.List;
import java.util.UUID;
import org.apache.ibatis.annotations.Param;

public interface DevDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int countByExample(DevDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int deleteByExample(DevDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int insert(DevDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int insertSelective(DevDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    List<DevDevice> selectByExample(DevDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    DevDevice selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") DevDevice record, @Param("example") DevDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExample(@Param("record") DevDevice record, @Param("example") DevDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKeySelective(DevDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKey(DevDevice record);
}