package com.royarn.mini.dao;

import com.royarn.mini.entity.Group;
import com.royarn.mini.entity.GroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    Group selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_groups
     *
     * @mbggenerated Fri Dec 28 12:36:51 CST 2018
     */
    int updateByPrimaryKey(Group record);

    void batchInsert(@Param("groups") List<Group> groups);

    List<Group> orderByGroup();
}