package com.royarn.mini.dao;

import com.royarn.mini.entity.LocalUser;
import com.royarn.mini.entity.LocalUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int countByExample(LocalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int deleteByExample(LocalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int insert(LocalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int insertSelective(LocalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    List<LocalUser> selectByExample(LocalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    LocalUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") LocalUser record, @Param("example") LocalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int updateByExample(@Param("record") LocalUser record, @Param("example") LocalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int updateByPrimaryKeySelective(LocalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 11 14:12:19 CST 2018
     */
    int updateByPrimaryKey(LocalUser record);

    /**
     * @param localUsers
     * @return
     */
    int batchInsert(@Param("localUsers") List<LocalUser> localUsers);
}