package com.royarn.mini.dao;

import com.royarn.mini.entity.TDevice;
import com.royarn.mini.entity.TDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int countByExample(TDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int deleteByExample(TDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int insert(TDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int insertSelective(TDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    List<TDevice> selectByExample(TDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    TDevice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") TDevice record, @Param("example") TDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int updateByExample(@Param("record") TDevice record, @Param("example") TDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int updateByPrimaryKeySelective(TDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_device
     *
     * @mbggenerated Fri Dec 28 16:41:25 CST 2018
     */
    int updateByPrimaryKey(TDevice record);

    List<TDevice> query4all();

    List<TDevice> orderBySort();
}