spring:
  aop:
    proxy-target-class: true
  messages:
    basename: i18n
  datasource:
    name: writedb
    #url: jdbc:mysql://192.168.12.76:7001/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
#    username: route
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  readdb:
    name: readdb
    #url: jdbc:mysql://192.168.12.76:7002/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    #username: route
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  application:
    name: mini
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage:
hostconf:
  host: 192.168.12.78
  port: 8080
management:
  endpoints:
    web:
      exposure:

        include: "*"
server:
  port: 9102
  tomcat:
    accesslog:
      enabled: false
    basedir: tomcat
#dubbo:
#  application:
#    name: mini
#  protocol:
#    name: dubbo
#    port: 20881
#  registry:
#    address: zookeeper://192.168.12.148:2181
mongodb:
  host: 172.16.34.208
  port: 27017
  dataSource: np_config
#kafka:
#  producer:
#    server: 192.168.12.148
#    retries: 0
#    batchSize: 4096
#    linger: 1
#    bufferMemory: 40960